# Generated by Django 6.0.1 on 2026-01-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_nuber',
            new_name='phone_number',
        ),
    ]
