# Generated by Django 6.0.1 on 2026-02-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
