# Generated by Django 6.0.1 on 2026-02-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_rattings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
